exports.indexListPage = function () {
  var html = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>TPC3 - EngWeb2024</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <header class="w3-teal w3-center">
            <h1><b>Filmes Americanos</b></h1>
        </header>
        <div class="w3-card-4 w3-center">
            <h2><b>Selecione uma das seguintes listas:</b></h2>
            <ul class="w3-ul w3-hoverable">
                <li><a href="http://localhost:7777/filmes"><b>Lista de Filmes</b></a></li>
                <li><a href="http://localhost:7777/atores"><b>Lista de Atores</b></a></li>
                <li><a href="http://localhost:7777/generos"><b>Lista de Generos</b></a></li>
            </ul>
        </div>


        <footer class="w3-container w3-teal w3-center">
            <h6><b>Generated by EngWeb2024</b></h6>
        </footer>
    </body>
</html>`

    return html
};

exports.filmsList = function(films)
{
    var html = `<!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8"/>
            <title>Lista de Filmes</title>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body>
        <header class="w3-teal w3-center">
            <h1><b>Filmes Americanos</b></h1>
        </header>
        <body>
            <div class="w3-container">
                <a href="http://localhost:7777/" class="w3-button w3-teal"><b>Voltar à página Inicial</b></a>
                <h2>Filmes Dísponiveis:</h2>
                <ul calss="w3-ul w3-card-4">`

        films.forEach(element => {
            html += `<li><a href="http://localhost:7777/filmes/${element.id}"><b>${element.title}</b><a/></li>`
        });       

        html += `
                </ul>
                <a href="http://localhost:7777/" class="w3-button w3-teal"><b>Voltar à página Inicial</b></a>
            </div>
            <footer class="w3-container w3-teal w3-center">
                <h6><b>Generated by EngWeb2024</b></h6>
            </footer>
        </body>
        </html>
        `
        return html
}

exports.genreList = function(genres)
{
    var html = `<!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8"/>
            <title>Lista de Generos</title>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body>
        <header class="w3-teal w3-center">
            <h1><b>Filmes Americanos</b></h1>
        </header>
        <body>
            <div class="w3-container">
                <a href="http://localhost:7777/" class="w3-button w3-teal"><b>Voltar à página Inicial</b></a>
                <h2>Generos Dísponiveis:</h2>
                <ul calss="w3-ul w3-card-4">`

            genres.forEach(element => {
            html += `<li><a href="http://localhost:7777/generos/${element.id}"><b>${element.nome}</b><a/></li>`
        });       


        html += `
                </ul>
                <a href="http://localhost:7777/" class="w3-button w3-teal"><b>Voltar à página Inicial</b></a>
            </div>
            <footer class="w3-container w3-teal w3-center">
                <h6><b>Generated by EngWeb2024</b></h6>
            </footer>
        </body>
        </html>
        `
        return html
}

exports.actorList = function(actors)
{
    var html = `<!DOCTYPE html>
    <html>
        <head>
            <meta charset="utf-8"/>
            <title>Lista de Atores</title>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body>
        <header class="w3-teal w3-center">
            <h1><b>Filmes Americanos</b></h1>
        </header>
        <body>
            <div class="w3-container">
                <a href="http://localhost:7777/" class="w3-button w3-teal"><b>Voltar à página Inicial</b></a>
                <h2>Atores/Atrizes Dísponiveis:</h2>
                <ul calss="w3-ul w3-card-4">`

            actors.forEach(element => {
            html += `<li><a href="http://localhost:7777/atores/${element.id}"><b>${element.nome}</b><a/></li>`
        });       


        html += `
                </ul>
                <a href="http://localhost:7777/" class="w3-button w3-teal"><b>Voltar à página Inicial</b></a>
            </div>
            <footer class="w3-container w3-teal w3-center">
                <h6><b>Generated by EngWeb2024</b></h6>
            </footer>
        </body>
        </html>
        `
        return html
}

exports.filmPage = function(film) {
    var html = `
    <html>
    <head>
        <title>${film.title} - Filmes Americanos</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <header class="w3-teal w3-center">
            <h1><b>Filmes Americanos</b></h1>
        </header>

        <div class="w3-container">
            <h2>Titulo: ${film.title}</h2>`
    
        html += `<p><b>Ano:</b> ${film.year}</p>`
        html += `<p><b>Generos:</b></p>
        <ul calss="w3-ul w3-card-4">`
        
        for(var key in film.genres)
        {
            html += `<li><a href="http://localhost:7777/generos/${key}">${film.genres[key]}</a></li>`
        }

        html += `</ul>`
        html += `<p><b>Elenco:</b></p>
        <ul calss="w3-ul w3-card-4">`

        for(var key in film.cast)
        {
            html += `<li><a href="http://localhost:7777/atores/${key}">${film.cast[key]}</a></li>`
        }

        html += `</ul>`
    
    html +=`<a href="http://localhost:7777/filmes" class="w3-button w3-teal"><b>Voltar à lista de Filmes</b></a>
            </div>
            <footer class="w3-container w3-teal w3-center">
                <h6><b>Generated by EngWeb2024</b></h6>
            </footer>
        </body>
    </html>
    `
    return html
}

exports.genrePage = function(genre) {
    var html = `
    <html>
    <head>
        <title>Genero ${genre.nome} - Filmes Americanos</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <header class="w3-teal w3-center">
            <h1><b>Filmes Americanos</b></h1>
        </header>

        <div class="w3-container">
            <h2>Genero: ${genre.nome}</h2>`
    
        html += `<p><b>Filmes deste Genero:</b></p>
        <ul calss="w3-ul w3-card-4">`
        
        for(var key in genre.filmes)
        {
            html += `<li><a href="http://localhost:7777/filmes/${key}">${genre.filmes[key]}</a></li>`
        }

        html += `</ul>`
        
    html +=`<a href="http://localhost:7777/generos" class="w3-button w3-teal"><b>Voltar à lista de Generos</b></a>
            </div>
            <footer class="w3-container w3-teal w3-center">
                <h6><b>Generated by EngWeb2024</b></h6>
            </footer>
        </body>
    </html>
    `
    return html
}

exports.actorPage = function(actor) {
    var html = `
    <html>
    <head>
        <title>Ator ${actor.nome} - Filmes Americanos</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <header class="w3-teal w3-center">
            <h1><b>Filmes Americanos</b></h1>
        </header>

        <div class="w3-container">
            <h2>Ator/Atriz: ${actor.nome}</h2>`
    
        html += `<p><b>Filmes em que participou:</b></p>
        <ul calss="w3-ul w3-card-4">`
        
        for(var key in actor.filmes)
        {
            html += `<li><a href="http://localhost:7777/filmes/${key}">${actor.filmes[key]}</a></li>`
        }

        html += `</ul>`
        
    html +=`<a href="http://localhost:7777/atores" class="w3-button w3-teal"><b>Voltar à lista de Atores</b></a>
            </div>
            <footer class="w3-container w3-teal w3-center">
                <h6><b>Generated by EngWeb2024</b></h6>
            </footer>
        </body>
    </html>
    `
    return html
}