services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    depends_on:
      - mongo-seed
  mongo-seed:
    image: mongo:latest
    volumes:
      - ./datasets/dataset.json:/dataset.json
    command: mongoimport --host mongodb -d fichaAfericao -c pessoas --type json --file dataset.json --jsonArray