

exports.compositoresListPage = function(compList) {
    var html = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores - Compositores Musicais</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-center w3-teal">
                    <h1><b>Compositores Musicais</b></h1>
                    <a href="/compositores" class="w3-button"><b>Lista de Compositores</b></a>
                    <a href="/periodos" class="w3-button"><b>Lista de Períodos</b></a>
                </header>
            <div class="w3-container">
            <div class="w3-cell-row" style="width:30%">
                <div class="w3-cell">
                    <h2><b>Lista de Compositores</b></h2> 
                </div>
                <div class="w3-cell">
                    <p><a href="/registo/compositores" class="w3-button w3-round w3-grey"><b>Adicionar Compositor</b></a></p>
                </div>
            </div>
                <table class="w3-table-all">
                    <tr>
                        <th>Nome</th>
                        <th>Data Nascimento</th>
                        <th>Data Obito</th>
                        <th>Período</th>
                        <th>Ações</th>
                    </tr>`

    compList.forEach(element => {
        html += `<tr>
                    <td><a href="/compositores/${element.id}">${element.nome}</a></td>
                    <td>${element.dataNasc}</td>
                    <td>${element.dataObito}</td>
                    <td><a href="/periodos/${element.periodo}">${element.periodo}</a></td>
                    <td>
                        [<a href="/edit/compositores/${element.id}">Editar</a>]
                        [<a href="/delete/compositores/${element.id}">Apagar</a>]
                    </td>
                 </tr>`
    });         

            html += `
                </table>                    
            </div>
            <footer class="w3-container w3-teal w3-center">
                <h6>Generated by <a href="https://github.com/mrmikept">Mike Pinto</a>. Powered by <a href="https://epl.di.uminho.pt/~jcr/AULAS/EngWeb2024/index.html">EngWeb2024</a></h6>
            </footer>
            </div>
        </body>
    </html>
    `
    return html
}

exports.periodosListPage = function(periodosList) {
    var html = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Períodos - Compositores Musicais</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-center w3-teal">
                    <h1><b>Compositores Musicais</b></h1>
                    <a href="/compositores" class="w3-button"><b>Lista de Compositores</b></a>
                    <a href="/periodos" class="w3-button"><b>Lista de Períodos</b></a>
                </header>
            <div class="w3-container">
            <div class="w3-cell-row" style="width:30%">
                <div class="w3-cell">
                    <h2><b>Lista de Períodos</b></h2> 
                </div>
                <div class="w3-cell">
                    <p><a href="/registo/periodos" class="w3-button w3-round w3-grey"><b>Adicionar Período</b></a></p>
                </div>
            </div>
                <table class="w3-table-all">
                    <tr>
                        <th>Designação</th>
                        <th>Século de Inicio</th>
                        <th>Século de Fim</th>
                        <th>Ações</th>
                    </tr>`

    periodosList.forEach(element => {
        html += `<tr>
                    <td><a href="/periodos/${element.id}">${element.id}</a></td>`
                    if(element.secInicio)
                    {
                        html += `<td>${element.secInicio}</td>`
                    }
                    else
                    {
                        html += `<td>Informação não dísponivel</td>`
                    }

                    if(element.secFim)
                    {
                        html += `<td>${element.secFim}</td>`
                    }
                    else
                    {
                        html += `<td>Informação não dísponivel</td>`
                    }
                    
                    html += `<td>
                        [<a href="/edit/periodos/${element.id}">Editar</a>]
                        [<a href="/delete/periodos/${element.id}">Apagar</a>]
                    </td>
                 </tr>`
    });         

            html += `
                </table>                    
            </div>
            <footer class="w3-container w3-teal w3-center">
                <h6>Generated by <a href="https://github.com/mrmikept">Mike Pinto</a>. Powered by <a href="https://epl.di.uminho.pt/~jcr/AULAS/EngWeb2024/index.html">EngWeb2024</a></h6>
            </footer>
            </div>
           
        </body>
    </html>
    `
    return html
}

exports.compositorPage = function(comp)
{
    var html = `
    <html>
    <head>
        <title>Compositor: ${comp.nome}</title>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-center w3-teal">
                <h1><b>Compositores Musicais</b></h1>
                <a href="/compositores" class="w3-button"><b>Lista de Compositores</b></a>
                <a href="/periodos" class="w3-button"><b>Lista de Períodos</b></a>
            </header>
            <h2 class="w3-center"><b>${comp.nome}</b></h2>
            <div class="w3-container w3-margin-bottom">
                <ul class="w3-ul w3-card-4">
                    <li><b>Data de Nascimento:</b> ${comp.dataNasc}</li>
                    <li><b>Data de Obito:</b> ${comp.dataObito}</li>
                    <li><b>Período:</b> <a href="/periodos/${comp.periodo}">${comp.periodo} </a></li>
                    <li><b>Biografia:</b> <p>${comp.bio}</p></li>
                </ul>
            </div>
            <div class="w3-cell w3-container">
                <a href="/compositores" class="w3-button w3-teal"><b>Voltar à lista de Compositores</b></a>
                <a href="/edit/compositores/${comp.id}" class="w3-button w3-blue"><b>Editar Compositor</b></a>
                <a href="/delete/compositores/${comp.id}" class="w3-button w3-red"><b>Apagar Compositor</b></a>
            </div>
            <footer class="w3-container w3-teal w3-center w3-margin-top">
                <h6>Generated by <a href="https://github.com/mrmikept">Mike Pinto</a>. Powered by <a href="https://epl.di.uminho.pt/~jcr/AULAS/EngWeb2024/index.html">EngWeb2024</a></h6>
            </footer>
        </div>
    </body>
    </html>
    `
    return html
}

exports.compositorFormPage = function(periodos)
{
    html = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Registro de Compositores</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-center w3-teal">
                    <h1><b>Compositores Musicais</b></h1>
                    <a href="/compositores" class="w3-button"><b>Lista de Compositores</b></a>
                    <a href="/periodos" class="w3-button"><b>Lista de Períodos</b></a>
                </header>
                <div class="w3-container">
                <h2 class="w3-center"><b>Registo de um compositor</b></h2>
                <form class="w3-container" method="POST">
                    <fildset>
                        <label><b>Id</b></label>
                        <input class="w3-input w3-round w3-border" type="text" name="id" required/>
                        <label><b>Nome</b></label>
                        <input class="w3-input w3-round w3-border" type="text" name="nome" required/>
                        <label><b>Data Nascimento</b></label>
                        <input class="w3-input w3-round w3-border" type="text" name="dataNasc"/>
                        <label><b>Data de Obíto</b></label>
                        <input class="w3-input w3-round w3-border" type="text" name="dataObito"/>
                        <label><b>Biografia</b></label>
                        <textarea class="w3-input w3-border w3-round" name="bio"/></textarea>
                        <label><b>Período</b></label>`
                    
                    periodos.forEach(periodo => {
                        html += `<br><input class="w3-radio w3-border" id="${periodo.id}" type="radio" name="periodo" value=${periodo.id} required/>`
                        html += `<label for="${periodo.id}">${periodo.id}</label><br>`
                    })
                    html += `<fildset>
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Registar Compositor</button>
                </form>
                </div>
                <footer class="w3-container w3-teal w3-center w3-margin-top">
                    <h6>Generated by <a href="https://github.com/mrmikept">Mike Pinto</a>. Powered by <a href="https://epl.di.uminho.pt/~jcr/AULAS/EngWeb2024/index.html">EngWeb2024</a></h6>
                </footer>
            </div>
        </body>
    </html>
    `
    return html
}

exports.compositorEditFormPage = function(comp)
{
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Edição do Compositor ${comp.nome}</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-center w3-teal">
                    <h1><b>Compositores Musicais</b></h1>
                    <a href="/compositores" class="w3-button"><b>Lista de Compositores</b></a>
                    <a href="/periodos" class="w3-button"><b>Lista de Períodos</b></a>
                </header>
                <h2 class="w3-center"><b>Edição de Compositor</b></h2>
                <form class="w3-container" method="POST">
                    <fildset>
                        <label><b>Id</b></label>
                        <input class="w3-input w3-border w3-round" type="text" name="id" readonly value="${comp.id}"/>
                        <label><b>Nome*</b></label>
                        <input class="w3-input  w3-border w3-round" type="text" name="nome" required value="${comp.nome}"/>
                        <label><b>Data Nascimento</b></label>
                        <input class="w3-input w3-border w3-round" type="text" name="dataNasc" value="${comp.dataNasc}"/>
                        <label><b>Data de Obíto</b></label>
                        <input class="w3-input w3-border w3-round" type="text" name="dataObito" value="${comp.dataObito}"/>
                        <label><b>Biografia</b></label>
                        <textarea class="w3-input w3-border w3-round" name="bio"/>${comp.bio}</textarea>
                        <label><b>Período</b></label>
                        <input class="w3-input w3-border w3-round" type="text" name="periodo" value="${comp.periodo}" readonly/>
                    <fildset>
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Guardar Alterações</button>
                </form>
                <footer class="w3-container w3-teal w3-center w3-margin-top">
                    <h6>Generated by <a href="https://github.com/mrmikept">Mike Pinto</a>. Powered by <a href="https://epl.di.uminho.pt/~jcr/AULAS/EngWeb2024/index.html">EngWeb2024</a></h6>
                </footer>
            </div>
        </body>
    </html>
    `
}

exports.periodoPage = function(periodo)
{
    var html = `
    <html>
    <head>
        <title>Periodo: ${periodo.designacao}</title>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-center w3-teal">
                <h1><b>Compositores Musicais</b></h1>
                <a href="/compositores" class="w3-button"><b>Lista de Compositores</b></a>
                <a href="/periodos" class="w3-button"><b>Lista de Períodos</b></a>
            </header>
            <h2 class="w3-center"><b>Período ${periodo.id}</b></h2>
            <div class="w3-container w3-margin-bottom">
                <ul class="w3-ul w3-card-4">`
                if(periodo.secInicio)
                {
                    html += `<li><b>Século de Início:</b> ${periodo.secInicio}</li>`
                }
                else
                {
                    html += `<li><b>Século de Início:</b> Informação não dísponivel.</li>`
                }
                if(periodo.secFim)
                {
                    html += `<li><b>Século de Fim:</b> ${periodo.secFim}</li>`
                }
                else
                {
                    html += `<li><b>Século de Fim:</b> Informação não dísponivel.</li>`
                }
                    html += `</ul>
            </div>
            <div class="w3-container">`
            if (periodo.compositores)
            {
                html += `<h3><b>Compositores deste Período:</b></h3>
                <ul class="w3-ul w3-card-4">`
                periodo.compositores.forEach(element => {
                    html += `<li><a href="/compositores/${element[0]}">${element[1]}</a></li>`
                })

            html += `</ul>`
            }
            
            html += `</div>
            <div class="w3-cell w3-container">
                <a href="/periodos" class="w3-button w3-teal"><b>Voltar à lista de Períodos</b></a>
                <a href="/edit/periodos/${periodo.id}" class="w3-button w3-blue"><b>Editar Período</b></a>
                <a href="/delete/periodos/${periodo.id}" class="w3-button w3-red"><b>Apagar Período</b></a>
            </div>
            <footer class="w3-container w3-teal w3-center w3-margin-top">
                <h6>Generated by <a href="https://github.com/mrmikept">Mike Pinto</a>. Powered by <a href="https://epl.di.uminho.pt/~jcr/AULAS/EngWeb2024/index.html">EngWeb2024</a></h6>
            </footer>
        </div>
    </body>
    </html>
    `
    return html
}

exports.periodoFormPage = function()
{
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Registro de Periodos</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-center w3-teal">
                    <h1><b>Compositores Musicais</b></h1>
                    <a href="/compositores" class="w3-button"><b>Lista de Compositores</b></a>
                    <a href="/periodos" class="w3-button"><b>Lista de Períodos</b></a>
                </header>
                <h2 class="w3-center"><b>Registo de um Periodo</b></h2>
                <form class="w3-container" method="POST">
                    <fildset>
                        <label><b>Designação</b></label>
                        <input class="w3-input w3-border w3-round" type="text" name="id" required/>
                        <label><b>Século de Início</b></label>
                        <input class="w3-input w3-border w3-round" type="text" name="secInicio"/>
                        <label><b>Século de Fim</b></label>
                        <input class="w3-input w3-border w3-round" type="text" name="secFim"/>
                    <fildset>
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Registar Periodo</button>
                </form>
                <footer class="w3-container w3-teal w3-center w3-margin-top">
                    <h6>Generated by <a href="https://github.com/mrmikept">Mike Pinto</a>. Powered by <a href="https://epl.di.uminho.pt/~jcr/AULAS/EngWeb2024/index.html">EngWeb2024</a></h6>
                </footer>
            </div>
        </body>
    </html>
    `
}

exports.periodoEditFormPage = function(periodo)
{
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Edição do Período ${periodo.id}/title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-center w3-teal">
                    <h1><b>Compositores Musicais</b></h1>
                    <a href="/compositores" class="w3-button"><b>Lista de Compositores</b></a>
                    <a href="/periodos" class="w3-button"><b>Lista de Períodos</b></a>
                </header>
                <h2 class="w3-center"><b>Edição do Período ${periodo.id}</b></h2>
                <form class="w3-container" method="POST">
                    <fildset>
                        <label><b>Designação</b></label>
                        <input class="w3-input w3-border w3-round" type="text" name="id" required value=${periodo.id} readonly/>
                        <label><b>Século de Início</b></label>
                        <input class="w3-input w3-border w3-round" type="text" name="secInicio" value=${periodo.secInicio}/>
                        <label><b>Século de Fim</b></label>
                        <input class="w3-input w3-border w3-round" type="text" name="secFim" value=${periodo.secFim}/>
                    <fildset>
                    <br/>
                    <button class="w3-btn w3-teal w3-mb-2" type="submit">Guardar Alterações</button>
                </form>
                <footer class="w3-container w3-teal w3-center w3-margin-top">
                    <h6>Generated by <a href="https://github.com/mrmikept">Mike Pinto</a>. Powered by <a href="https://epl.di.uminho.pt/~jcr/AULAS/EngWeb2024/index.html">EngWeb2024</a></h6>
                </footer>
            </div>
        </body>
    </html>
    `
}

exports.infoPage = function(title,message)
{
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <title>${title}</title>
            <meta charset="UTF-8"/>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
            <header class="w3-container w3-center w3-teal">
                <h1><b>Compositores Musicais</b></h1>
                <a href="/compositores" class="w3-button"><b>Lista de Compositores</b></a>
                <a href="/periodos" class="w3-button"><b>Lista de Períodos</b></a>
            </header>
                <div class="w3-container w3-center"> 
                    <h2><b>${title}</b></h2>
                    <p>${message}</p>
                </div>
                <footer class="w3-container w3-teal w3-center w3-margin-top">
                    <h6>Generated by <a href="https://github.com/mrmikept">Mike Pinto</a>. Powered by <a href="https://epl.di.uminho.pt/~jcr/AULAS/EngWeb2024/index.html">EngWeb2024</a></h6>
                </footer>
            <div>
        </body>
    </html>
    `
}